# Generated by Django 6.0.1 on 2026-02-09 11:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('number', models.CharField(blank=True, max_length=50, verbose_name='Invoice Number')),
                ('invoice_type', models.CharField(choices=[('invoice', 'Invoice'), ('simplified', 'Simplified Invoice'), ('rectifying', 'Rectifying Invoice')], default='invoice', max_length=20, verbose_name='Type')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Issue Date')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('customer_tax_id', models.CharField(blank=True, max_length=50, verbose_name='Customer Tax ID')),
                ('customer_address', models.TextField(blank=True, verbose_name='Customer Address')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Customer Email')),
                ('customer_phone', models.CharField(blank=True, max_length=50, verbose_name='Customer Phone')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Subtotal')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5, verbose_name='Tax Rate %')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Tax Amount')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Payment Method')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Paid Amount')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid At')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='customers.customer', verbose_name='Customer')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.localuser', verbose_name='Employee')),
                ('rectified_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rectifying_invoices', to='invoicing.invoice', verbose_name='Rectified Invoice')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='sales.sale', verbose_name='Sale')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'invoicing_invoice',
                'ordering': ['-issue_date', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('product_sku', models.CharField(blank=True, max_length=50, verbose_name='SKU')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=10, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unit Price')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Discount %')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5, verbose_name='Tax Rate %')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Line Total')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoicing.invoice', verbose_name='Invoice')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Invoice Line',
                'verbose_name_plural': 'Invoice Lines',
                'db_table': 'invoicing_line',
                'ordering': ['order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('prefix', models.CharField(max_length=10, verbose_name='Prefix')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('next_number', models.PositiveIntegerField(default=1, verbose_name='Next Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default Series')),
                ('number_digits', models.PositiveSmallIntegerField(default=6, verbose_name='Number Digits')),
            ],
            options={
                'verbose_name': 'Invoice Series',
                'verbose_name_plural': 'Invoice Series',
                'db_table': 'invoicing_series',
                'ordering': ['prefix'],
                'abstract': False,
                'unique_together': {('hub_id', 'prefix')},
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoicing.invoiceseries', verbose_name='Series'),
        ),
        migrations.CreateModel(
            name='InvoicingSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Company Name')),
                ('company_tax_id', models.CharField(blank=True, max_length=50, verbose_name='Tax ID (NIF/CIF)')),
                ('company_address', models.TextField(blank=True, verbose_name='Address')),
                ('company_phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
                ('company_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('default_series_prefix', models.CharField(default='F', max_length=10, verbose_name='Default Series Prefix')),
                ('auto_generate_invoice', models.BooleanField(default=False, verbose_name='Auto-generate on Sale')),
                ('require_customer', models.BooleanField(default=True, verbose_name='Require Customer')),
                ('invoice_footer', models.TextField(blank=True, help_text='Text shown at the bottom of invoices', verbose_name='Invoice Footer')),
            ],
            options={
                'verbose_name': 'Invoicing Settings',
                'verbose_name_plural': 'Invoicing Settings',
                'db_table': 'invoicing_settings',
                'abstract': False,
                'unique_together': {('hub_id',)},
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['hub_id', 'number'], name='invoicing_i_hub_id_059a6c_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['hub_id', 'status'], name='invoicing_i_hub_id_3ab668_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['hub_id', 'issue_date'], name='invoicing_i_hub_id_3466aa_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['hub_id', 'customer_tax_id'], name='invoicing_i_hub_id_e3706e_idx'),
        ),
    ]
