# Generated by Django 6.0 on 2025-12-25 16:13

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=10, unique=True, verbose_name='Prefix')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('next_number', models.PositiveIntegerField(default=1, verbose_name='Next Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default Series')),
                ('number_digits', models.PositiveSmallIntegerField(default=6, verbose_name='Number Digits')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invoice Series',
                'verbose_name_plural': 'Invoice Series',
                'ordering': ['prefix'],
            },
        ),
        migrations.CreateModel(
            name='InvoicingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Company Name')),
                ('company_tax_id', models.CharField(blank=True, max_length=50, verbose_name='Tax ID (NIF/CIF)')),
                ('company_address', models.TextField(blank=True, verbose_name='Address')),
                ('company_phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
                ('company_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('default_series', models.CharField(default='F', max_length=10, verbose_name='Default Series')),
                ('auto_generate_invoice', models.BooleanField(default=False, verbose_name='Auto-generate on Sale')),
                ('require_customer', models.BooleanField(default=True, verbose_name='Require Customer')),
                ('invoice_footer', models.TextField(blank=True, help_text='Text to show at the bottom of invoices', verbose_name='Invoice Footer')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invoicing Configuration',
                'verbose_name_plural': 'Invoicing Configuration',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Invoice Number')),
                ('invoice_type', models.CharField(choices=[('invoice', 'Invoice'), ('simplified', 'Simplified Invoice'), ('rectifying', 'Rectifying Invoice')], default='invoice', max_length=20, verbose_name='Type')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Issue Date')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('customer_tax_id', models.CharField(blank=True, max_length=50, verbose_name='Customer Tax ID')),
                ('customer_address', models.TextField(blank=True, verbose_name='Customer Address')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Customer Email')),
                ('customer_phone', models.CharField(blank=True, max_length=50, verbose_name='Customer Phone')),
                ('customer_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Customer ID')),
                ('sale_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sale ID')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Subtotal')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5, verbose_name='Tax Rate %')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Tax Amount')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Payment Method')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Paid Amount')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid At')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rectified_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rectifying_invoices', to='invoicing.invoice', verbose_name='Rectified Invoice')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoicing.invoiceseries', verbose_name='Series')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Product ID')),
                ('product_sku', models.CharField(blank=True, max_length=50, verbose_name='SKU')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=10, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unit Price')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Discount %')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5, verbose_name='Tax Rate %')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Line Total')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoicing.invoice', verbose_name='Invoice')),
            ],
            options={
                'verbose_name': 'Invoice Line',
                'verbose_name_plural': 'Invoice Lines',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['number'], name='invoicing_i_number_fe55ac_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='invoicing_i_status_2eeee5_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['issue_date'], name='invoicing_i_issue_d_436aef_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer_tax_id'], name='invoicing_i_custome_aa8096_idx'),
        ),
    ]
