# Generated by Django 6.0.2 on 2026-03-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Customer Name'),
        ),
    ]
