# Generated by Django 6.0.2 on 2026-03-26 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('invoicing', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='sales.sale', verbose_name='Sale'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoicing.invoice', verbose_name='Invoice'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.product', verbose_name='Product'),
        ),
        migrations.AlterUniqueTogether(
            name='invoiceseries',
            unique_together={('hub_id', 'prefix')},
        ),
        migrations.AddField(
            model_name='invoice',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoicing.invoiceseries', verbose_name='Series'),
        ),
        migrations.AlterUniqueTogether(
            name='invoicingsettings',
            unique_together={('hub_id',)},
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['hub_id', 'number'], name='invoicing_i_hub_id_059a6c_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['hub_id', 'status'], name='invoicing_i_hub_id_3ab668_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['hub_id', 'issue_date'], name='invoicing_i_hub_id_3466aa_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['hub_id', 'customer_tax_id'], name='invoicing_i_hub_id_e3706e_idx'),
        ),
    ]
